### ISSUE TITLE
Week #0 To-Do

### ISSUE THREAD

**Issue by HexicPyth** [FRC3236/DeepSpace#24]
_We have two days to get the robot at least minimally working_
**Important Tasks due Saturday 2/16**

- [x] - [Program Linear Actuator + Hall Effect Sensor](https://github.com/FRC3236/DeepSpace/issues/25)
- [x] - [Configure Pneumatic controls for _Hatch Thingy_](https://github.com/FRC3236/DeepSpace/issues/27)
- [x] - [Configure motor controls for _Ball Thingy_](https://github.com/FRC3236/DeepSpace/issues/28)
- [x] - [Configure a second motor for Elevator](https://github.com/FRC3236/DeepSpace/issues/29)
- [x] - [Merge messy branches](https://github.com/FRC3236/DeepSpace/issues/30)
- [ ] - [Make Driving controls Intuitive forwards/backwards](https://github.com/FRC3236/DeepSpace/issues/31) (Relies on [Merging Messy Branches](https://github.com/FRC3236/DeepSpace/issues/30))
